apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-k8s-back
  labels:
    app: mern-k8s
    component: back
spec:
  replicas: 2
  selector: 
    matchLabels:
      component: back
  template:
    metadata: 
      labels:
        app: mern-k8s
        component: back
    spec:
      containers:
        - name: mern-k8s-back
          image: cedricclyburn/mern-k8s-back
          ports: 
            - containerPort: 5050
          env: 
            - name: PORT
              value: "5000"
            - name: CONN_STR
              value: "$ATLAS_CONNECTION_STRING"
---
apiVersion: v1
kind: Service
metadata:
  name: mern-k8s-back
  labels:
    app: mern-k8s
    component: back
spec:
  selector:
    component: back
  ports:
    - port: 80
      targetPort: 5050
      protocol: TCP
      name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-k8s-front
  labels:
    app: mern-k8s
    component: front
spec:
  replicas: 2
  selector: 
    matchLabels:
      component: front
  template:
    metadata: 
      labels:
        app: mern-k8s
        component: front
    spec:
      containers:
        - name: mern-k8s-front
          image: cedricclyburn/mern-k8s-front
          ports: 
            - containerPort: 80
          env: 
            - name: BASE_URL
              value: "/api"
---
apiVersion: v1
kind: Service
metadata:
  name: mern-k8s-front
  labels:
    app: mern-k8s
    component: front
spec:
  selector:
    component: front
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mern-k8s-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - http:
        paths:
          - path: /api(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: mern-k8s-back
                port:
                  number: 80
          - path: /()(.*)
            pathType: Prefix
            backend:
              service:
                name: mern-k8s-front
                port:
                  number: 80