apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-demo-k8s-frontend
  labels:
    app: mern-demo-k8s
    component: frontend
spec:
  replicas: 1
  selector: 
    matchLabels:
      component: frontend
  template:
    metadata: 
      labels:
        app: mern-demo-k8s
        component: frontend
    spec:
      containers:
        - name: mern-demo-k8s-frontend
          image: cedricclyburn/mern-demo-k8s-frontend
          ports: 
            - containerPort: 80
          env: 
            - name: BASE_URL
              value: "http://api.mern-k8s.com"